### ISSUE TITLE
Erron in importing genometools

### ISSUE THREAD

**Issue by ernestopicardi** [flo-compbio/gopca#10]
Hi,
I have installed genometools using pip. No error messages were generated during the installation. However, I'm not able to import the module. I always get the following error:
Python 2.7.10 (default, Oct 11 2015, 15:42:07)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import genometools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/epicardi/bin/python27/lib/python2.7/site-packages/genometools/__init__.py", line 24, in <module>
    __version__ = pkg_resources.require('genometools')[0].version
  File "/home/epicardi/bin/python27/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/epicardi/bin/python27/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: genometools

As you can see, I'm using python 2.7.10 running on Linux CentOS.
Any help is very welcome.
Best,
Ernesto

**Comment by flo-compbio** [comment]
Hi Ernesto,

It's a little bit difficult to diagnose the problem given this error message. Importing `genometools` works for me. Maybe there's a problem with your installation? Can you try to install the latest version of the `gopca` package and see if the error persists?

To install the latest version:
 `pip install gopca==0.2.2` or
  `pip install --user gopca==0.2.2` (to install the package for your user only)

Best, Flo

**Comment by ernestopicardi** [comment]
Solved! Many thanks. 
I have re-installed python and gopca following your suggestions.

Best,
Ernesto
